version: "3.7"
services:
  donem_projesi_webserver:
    build: .
    ports:
      - "80:80"
    depends_on:
      - donem_projesi_mysql
    command: '/bin/bash /usr/local/bin/application.sh'
    volumes:
      - ../../donem_projesi:/home/web/donem_projesi
    networks:
      - donem_projesi_node_net

  donem_projesi_mysql:
    image: mysql:5.7
    command: --max_allowed_packet=20G
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donem_projesi
    networks:
      donem_projesi_node_net:
        ipv4_address: 170.46.0.3

  donem_projesi_phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOST=donem_projesi_mysql
      - MYSQL_ROOT_PASSWORD=root
    networks:
      donem_projesi_node_net:
        ipv4_address: 170.46.0.5
networks:
  donem_projesi_node_net:
    ipam:
      driver: default
      config:
        - subnet: 170.46.0.0/16